### ISSUE TITLE
How connect to intel aero board with using USB cable 

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#256] opened 2017-08-07 12:17 UTC
I try connect to intel aero board with using USB cable via putty program but isnt successful. There are another way or what i missed? If i switch wifi mode from access point to client mode,  will be able still connect to drone board with using ssh?

**Comment by lucasdemarchi** [comment] 2017-08-07 13:54
What version of Aero are you using? What OS objetivos your computer?

**Comment by Aurusd** [comment] 2017-08-07 14:20
INTEL® AERO READY TO FLY DRONE with 4.4.3 yocto standart

**Comment by Aurusd** [comment] 2017-08-07 14:21
Operating System | Yocto Project 2.1 (Krogoth), Linux* 4.4.3-yocto-standard

**Comment by Aurusd** [comment] 2017-08-07 14:25
I use usb3.0 to usb or microUSB to USB cables, board detect like COM3 on PC, but i cant make connection via putty

**Comment by avinash-palleti** [comment] 2017-08-07 16:28
@Aurusd Are you getting new network interface in your host machine when you connect to Aero Board using USB cable?

If Yes, then it is ready to connect through SSH. If No, there should be some issue with either cable or usb drivers on host machine. Can you help us providing dmesg logs from your host machine after you connect USB Cable.

To get OS version you can run aero-get-version.py on Aero board which is available by default.

**Comment by lucasdemarchi** [comment] 2017-08-07 17:22
> Operating System | Yocto Project 2.1 (Krogoth), Linux* 4.4.3-yocto-standard

This is before Aero 1.2.  In that version it doesn't get an IP via dhcp so you will need to set it manually.  However, you should rather update Aero:
https://intel-aero.github.io/getting-started/update

I was also asking by your host OS (i.e. the one on your computer/laptop).  The usb-ethernet works on Linux and Mac. On Windows it may or may not work depending on drivers installed.

**Comment by lucasdemarchi** [comment] 2017-08-07 17:23
See #154

**Comment by Aurusd** [comment] 2017-08-07 18:41
When i used aero-get-version.py - result is nit successful, command not found

**Comment by lucasdemarchi** [comment] 2017-08-07 18:45
See the link to the update section above. If you don't have this command it means you have version before 1.2

**Comment by Aurusd** [comment] 2017-08-07 18:47
On my windows PC, when i connect aero board with using usb cable, windows detected com port COM3, but putty isnt connect via this port

**Comment by Aurusd** [comment] 2017-08-07 18:48
ok, thanks lucasdemarchi, i will try tomorrow to update

**Comment by Aurusd** [comment] 2017-08-08 09:51
i have been install 1.4 version and activate wifi on aero drone. Have connection via ssh but still dont understand how to connect to drone via usb cable?

**Comment by Aurusd** [comment] 2017-08-08 09:53
and another question, how can i install java on drone? use this link https://thelinuxfaq.com/473-yocto-how-to-install-java-jdk-in-intel-edision-board on edison, its work fine but on aero  it isnt work, have you any advices?

**Comment by avinash-palleti** [comment] 2017-08-08 10:25
@Aurusd Can you please provide the error you got while following the installation steps.

And regarding ssh via USB cable, on your windows machine did you install RNDIS Ethernet driver because that's what it is asking me to install if i connect to my windows pc.
If Yes, Can you provide ifconfig output on Aero board.

**Comment by Aurusd** [comment] 2017-08-08 11:45
![clip2net_170808144554](https://user-images.githubusercontent.com/10154188/29070483-41c6b4b8-7c48-11e7-812d-fa95f174f0e1.png)

**Comment by Aurusd** [comment] 2017-08-08 11:49
if i connect usb cable i have never see any message for install something
[http://clip2net.com/s/3MM2ieP](url)

**Comment by Aurusd** [comment] 2017-08-08 11:58
via ssh with usin usb cable connect yo 192.168.7.2 isnt successful

**Comment by avinash-palleti** [comment] 2017-08-08 15:13
@Aurusd As ifconfig on Aero showing that USB interface is up and ip-address is also assigned to it, so there is no issue from Aero side. Below is the screenshot what i see when i connect Aero to windows pc.

![updatedriversoftwarewindow](https://user-images.githubusercontent.com/362099/29079063-c80867f2-7c79-11e7-92eb-f36b65b75578.jpg)

And also from screenshot i can see you are trying to connect through serial interface in putty. Can you give try with SSH and with 192.168.7.2 address and root as username.

**Comment by lucasdemarchi** [comment] 2017-08-08 16:08
@avinash-palleti what version of Windows are you using? Can you take a look on the doc section about usb on windows and correct any problem there?

**Comment by avinash-palleti** [comment] 2017-08-08 16:10
sure @lucasdemarchi

**Comment by Aurusd** [comment] 2017-08-08 19:11
Windows 10, and i also try 192.168.7.2 address and root as username instead of serial interface, but still no connection. When connect aero vai usb cable there isnt any other device. I think its maybe because win10 use some standard driver

**Comment by Aurusd** [comment] 2017-08-08 19:16
i have try driver toolkit program, and saw that there isnt driver for USB/LPT port (RNDIS/Ethernet gadget), but program didnt download it.  Maybe its problem on win 10

**Comment by Aurusd** [comment] 2017-08-08 19:23
its something like here https://www.mobileread.com/forums/showthread.php?p=3283986
On Windows 10, when jailbroken Kindle with enabled USBNet is plugged via USB, it will appear as a "Serial USB device (COM3)" in device manager.
If Windows 10 already recognized your Kindle device as an extra network card, you do not need this driver package :3
i have download driver files from http://www.driverscape.com/download/rndis-ethernet-gadget and do the same action but driver isnt update

**Comment by avinash-palleti** [comment] 2017-08-09 03:35
@Aurusd I am using windows 8.1, after installing RNDIS driver, in device manager you should see new device in network adapters section like below,

![untitled](https://user-images.githubusercontent.com/362099/29104051-dd17a2a4-7ce0-11e7-984e-ffefd5fc839e.png)

I took driver from the same link which you shared above, http://www.driverscape.com/download/rndis-ethernet-gadget.
Please follow driver update process as mentioned in below link,
https://www.lifewire.com/updating-drivers-in-windows-7-tutorial-2619224

After that i am able to do ssh using putty from my windows PC.

![untitled2](https://user-images.githubusercontent.com/362099/29104208-bf4e758a-7ce1-11e7-8935-942d6308ad60.png)
![untitled3](https://user-images.githubusercontent.com/362099/29104212-c686990e-7ce1-11e7-9e58-5edc5cf77960.png)

**Comment by Aurusd** [comment] 2017-08-09 06:36
try today on win7.. everything work fine like you described before, on win 10 no device.
![clip2net_170809093603](https://user-images.githubusercontent.com/10154188/29108106-22709f40-7ce6-11e7-8359-b58bf7669785.png)

**Comment by lucasdemarchi** [comment] 2017-08-09 06:48
Solution seems to be here:
https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/windows-10-vs-remote-ndis-ethernet-usbgadget-not/cb30520a-753c-4219-b908-ad3d45590447

tldtr: a bug in windows 10 that doesn't declare that usb descriptor as compatible with rndis.

For the current version (1.5.1) I think we should document the solution 1 described there:

> Solution 1: If you are one of the people that found this because your device is showing up as a COM port instead of RNDIS, you may be able to get away using the RNDIS 5.1 driver. Find your device under Ports (COM & LTP) in Device Manager. Right-click it and select Update Driver Software..., then Browse my computer for driver software and then Let me pick from a list of device drivers on my computer and finally choose Remote NDIS Compatible Device. This should install the Microsoft RNDIS 5.1 driver (shows "Acer" as the manufacturer). If this works great. If it causes Network and Settings and other network related things to lock up, then you need the RNDIS 6.0 driver instead. Try one of the other solutions.

For next version we may investigate solution 2:

> Solution 2: If you have control over the RNDIS device and it runs Linux (i.e. BeagleBone), you can tweak the driver to get along with Windows better. For example, if you have a 3.16 kernel or newer, you can setup your gadget using configfs and include os descriptors. This is actually what I ended up doing for my case. You can find my fully documented script here. The key was specifying the compatible and subcompatible ids so that it matches "USB\MS_COMP_RNDIS&MS_SUBCOMP_5162001" in rndiscmp.inf. This causes the Microsoft RNDIS 6.0 driver to be installed for this device. With this driver, I have not seen the same lockup as I have with the 5.1 (Acer) driver. I also changed the vendor and product ids so that it wouldn't match the "Acer" driver.

Btw I think that recent versions of Debian that comes on BBB and BB Blue is doing exactly that. We may take a look on how they are doing that. Just need to take care that the same USB port can be a host port.

Thanks all for the testing and feedback.

**Comment by Aurusd** [comment] 2017-08-09 07:19
Solution 1 didnt work..((

**Comment by avinash-palleti** [comment] 2017-08-10 03:47
@Aurusd Can you please confirm if any of the solution from above link worked for you.
> https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/windows-10-vs-remote-ndis-ethernet-usbgadget-not/cb30520a-753c-4219-b908-ad3d45590447

**Comment by Aurusd** [comment] 2017-08-10 06:47
Like here it helps
Download & Unzip attachment kindle_rndis.inf_amd64-v1.0.0.1.zip
R-click "5-runasadmin_register-CA-cer.cmd" and "Run as administrator"*
In Device Manager, expand "Ports (COM & LPT)", R-click "Serial USB device (COM3)" > Update Driver Software...
Browse for my computer for driver software > Select extract folder
But! still no connection with aero drone via qGroundControl application(

**Comment by sugnanprabhu** [comment] 2017-08-10 08:34
@Aurusd 

Please try the following. I tried the following steps on Win 10 and see that the issue is resolved.

https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/windows-10-vs-remote-ndis-ethernet-usbgadget-not/cb30520a-753c-4219-b908-ad3d45590447?auth=1

> `Thanks a lot Andrea !
Worked for me with the Raspberry Pi Zero.
Reddit redirects to a french tutorial that gives driver files, here are the direct links for future readers:
Tutorial: http://domotique.caron.ws/cartes-microcontroleurs/raspberrypi/pi-zero-otg-ethernet/
Driver files: http://domotique.caron.ws/wp-content/uploads/telechargement/RPI%20Driver%20OTG.zip
`
> `Just click "search my computer..." and give the path to the downloaded folder. The device will be recognized as a RNDIS Gadget.
`

**Comment by sugnanprabhu** [comment] 2017-08-14 02:24
@Aurusd Can you confirm if the issue is resolve with the above steps?

**Comment by Aurusd** [comment] 2017-08-14 06:25
help only this
Download & Unzip attachment kindle_rndis.inf_amd64-v1.0.0.1.zip
R-click "5-runasadmin_register-CA-cer.cmd" and "Run as administrator"*
In Device Manager, expand "Ports (COM & LPT)", R-click "Serial USB device (COM3)" > Update Driver Software...
Browse for my computer for driver software > Select extract folder

**Comment by zehortigoza** [comment] 2017-09-29 18:19
@Aurusd can the be closed? I think you already have a working setup.

**Comment by lucasdemarchi** [comment] 2017-10-19 15:19
I think this can now be closed

**Closed by lucasdemarchi** 2017-10-19 15:19 UTC
Labels: comms
